version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
    time: "10:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: sidekiq
    versions:
    - ">= 6.a, < 7"
  - dependency-name: listen
    versions:
    - 3.4.1
    - 3.5.0
  - dependency-name: rspec-rails
    versions:
    - 4.1.0
    - 5.0.0
  - dependency-name: rails
    versions:
    - 6.1.1
    - 6.1.2
    - 6.1.2.1
    - 6.1.3
  - dependency-name: sdoc
    versions:
    - 2.0.4
  - dependency-name: puma
    versions:
    - 5.2.1
  - dependency-name: nokogiri
    versions:
    - 1.11.1
